spring:
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myfourm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    protocol: smtps
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱
    username: ysu_vic@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: JTGWOUXGXTYQGTDE
    # 端口号465或587
    #    port: 465
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8

mybatis-plus:
  #mapper文件定位
  mapper-locations: classpath*:/mapper/*.xml
  #开启包的别名
  type-aliases-package: cn.myfourm.entity
  configuration:
    #开启自动驼峰命名转换
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8182

virtualImgUrl: http://localhost:8182/img/
virtualVideoUrl: http://localhost:8182/video/
imgPath: E:/picture/
videoPath: E:/video/

redis:
  # Redis数据库索引（默认为 0）
  database: 0
  # Redis服务器地址
  host: localhost
  # Redis服务器连接端口
  port: 6379
  # Redis 密码
  #password: root
  lettuce:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 8
      # 连接池中的最大空闲连接
      max-idle: 500
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 2000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
  # 连接超时时间（毫秒）
  timeout: 5000